apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finspherex
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [bank.example.com, api.example.com]
      secretName: finspherex-tls
  rules:
    - host: bank.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: finspherex-web
                port:
                  number: 3000
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: finspherex-api
                port:
                  number: 8000
