import {
  Activity,
  ArrowLeftRight,
  Banknote,
  Bell,
  BriefcaseBusiness,
  ClipboardList,
  CreditCard,
  FileText,
  Globe2,
  HandCoins,
  Landmark,
  LifeBuoy,
  LayoutDashboard,
  PlugZap,
  ScanSearch,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  TrendingUp,
  Target,
  UserRound,
  UsersRound,
  Wallet,
} from "lucide-react";

export const customerNavigation = [
  ["/dashboard", "Overview", LayoutDashboard],
  ["/accounts", "Accounts", Banknote],
  ["/wallet", "Wallet", Wallet],
  ["/transfers", "Transfers", ArrowLeftRight],
  ["/payments", "Payments", Activity],
  ["/cards", "Cards", CreditCard],
  ["/deposits", "Term deposits", Landmark],
  ["/budgets", "Budgets", Banknote],
  ["/goals", "Savings goals", Target],
  ["/statements", "Statements", FileText],
  ["/profile", "Profile & KYC", UserRound],
  ["/security", "Security", ShieldCheck],
  ["/notifications", "Notifications", Bell],
  ["/support", "Support", LifeBuoy],
  ["/onboarding", "Onboarding", ClipboardList],
] as const;

export const operationsNavigation = [
  ["/dashboard", "Overview", LayoutDashboard],
  ["/notifications", "Activity", Bell],
  ["/support", "Support queue", LifeBuoy],
  ["/kyc", "KYC review", ShieldCheck],
  ["/loans", "Loan review", HandCoins],
  ["/collections", "Collections", ClipboardList],
  ["/business-review", "Business review", BriefcaseBusiness],
  ["/payroll-review", "Payroll approvals", ClipboardList],
  ["/settlement-review", "Settlement review", Banknote],
  ["/expense-review", "Expense review", ClipboardList],
  ["/merchant-disputes", "Disputes", ShieldCheck],
  ["/finance", "Finance & ledger", Landmark],
  ["/risk", "Risk casework", ScanSearch],
  ["/treasury", "Liquidity", Wallet],
  ["/remittance-review", "Remittance review", Globe2],
] as const;

export const roleNavigation = {
  customer: [
    ...customerNavigation.slice(0, 6),
    ["/deposits", "Term deposits", Landmark],
    ["/budgets", "Budgets", Banknote],
    ["/goals", "Savings goals", Target],
    ["/loans", "Loans", HandCoins],
    ["/bnpl", "Buy now, pay later", ShoppingBag],
    ["/investments", "Investments", TrendingUp],
    ["/fx-remittance", "FX & remittance", Globe2],
    ["/copilot", "Money copilot", Sparkles],
    ["/open-banking", "Data consents", PlugZap],
    ...customerNavigation.slice(6),
  ],
  operations: operationsNavigation,
  admin: [
    ...operationsNavigation,
    ["/developer", "Developer platform", PlugZap],
    ["/members", "Members & accounts", UsersRound],
  ],
  business: [
    ["/dashboard", "Overview", LayoutDashboard],
    ["/business", "Business", BriefcaseBusiness],
    ["/payroll", "Payroll", ClipboardList],
    ["/expenses", "Expense claims", Banknote],
  ],
  merchant: [
    ["/dashboard", "Overview", LayoutDashboard],
    ["/merchant", "Settlements", Landmark],
    ["/merchant-transactions", "Sales & refunds", Activity],
    ["/merchant-disputes", "Disputes", ShieldCheck],
  ],
} as const;
